# - Try to locate SDL2_gfx
# This module defines:
#
#  SDL2_GFX_INCLUDE_DIR
#  SDL2_GFX_LIBRARY
#  SDL2_GFX_FOUND
#

FIND_PATH(SDL2_GFX_INCLUDE_DIR NAMES SDL2_framerate.h SDL2_gfxPrimitives.h SDL2_rotozoom.h PATH_SUFFIXES SDL2)

FIND_LIBRARY(SDL2_GFX_LIBRARY NAMES SDL2_gfx)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_gfx REQUIRED_VARS SDL2_GFX_LIBRARY SDL2_GFX_INCLUDE_DIR)

MARK_AS_ADVANCED(SDL2_GFX_INCLUDE_DIR SDL2_GFX_LIBRARY)
